CREATE TABLE LITEMALL.BRAND (
	ID INTEGER NOT NULL,
	NAME VARCHAR(255),
	CONSTRAINT BRAND_PK PRIMARY KEY (ID)
);

CREATE TABLE LITEMALL.DWD_DIM_SKU (
	ID INTEGER NOT NULL,
	NAME VARCHAR(200),
	CATEGORY_ID INTEGER,
	BRAND_ID INTEGER,
	CATEGORY_NAME VARCHAR(63),
	BRAND_NAME VARCHAR(255),
	CONSTRAINT DWD_DIM_SKU_PK PRIMARY KEY (ID)
);

CREATE TABLE LITEMALL.GOODS_CATEGORY (
	ID INTEGER NOT NULL,
	NAME VARCHAR(63),
	CONSTRAINT GOODS_CATEGORY_PK PRIMARY KEY (ID)
);

CREATE TABLE LITEMALL.REGION (
	ID INTEGER NOT NULL,
	NAME VARCHAR(100),
	CODE INTEGER,
	CONSTRAINT REGION_PK PRIMARY KEY (ID)
);

CREATE TABLE LITEMALL.USERS (
	ID INTEGER NOT NULL,
	USERNAME VARCHAR(63),
	GENDER VARCHAR(6),
	BIRTHDAY DATE,
	LAST_LOGIN_TIME DATE,
	LAST_LOGIN_IP VARCHAR(20),
	USER_LEVEL SMALLINT,
	NICKNAME VARCHAR(63),
	AGE_GROUP VARCHAR(10),
	CONSTRAINT USERS_PK PRIMARY KEY (ID)
);

CREATE TABLE LITEMALL.USER_ORDER_STATUS (
	USER_ID BIGINT NOT NULL,
	IS_FIRST BOOLEAN,
	CONSTRAINT USER_ORDER_STATUS_PK PRIMARY KEY (USER_ID)
);